version: '2'

services:
        blockchain-api:
                image: ducatus-api
                command: tail -f /dev/random
                volumes:
                        - blockchain-api-volume:/root/.ducatuscoin
                        - ./ducatuscoin.conf:/root/.ducatuscoin/ducatuscoin.conf
                ports:
                        - "3001:3001"

        ducatuscoin:
                image: ducatuscoin
                command: bash -c 'ducatuscoind; tail -f /root/.ducatuscoin/debug.log'
                ports:
                        - "9690:9690"
                        - "9691:9691"
                volumes:
                        - ducatuscoin-volume:/root/.ducatuscoin
                        - ./ducatuscoin.conf:/root/.ducatuscoin/ducatuscoin.conf

volumes:
        ducatuscoin-volume:
        blockchain-api-volume:
