version: '3.7'

services:

  ducatuscoin_node:
    image: rnbdeploy/ducatuscoin:latest
    build:
        context: .
        dockerfile: Dockerfile
    # command: bash -c 'ducatuscoind; sleep 1; tail -f /root/.ducatuscoin/testnet4/debug.log'
    # command: bash -c "sleep 10000"
    command: ducatuscoind
    restart: always
    ports:
      - "18335:18335"
      - "18336:18336"
    volumes:
      # - ./ducatuscoin.conf:/root/.ducatuscoin/ducatuscoin.conf
      - ./testnet-conf/ducatus_test.conf:/root/.ducatuscoin/ducatuscoin.conf
      - ./.docker/node_data:/root/.ducatuscoin/testnet4

  ducatuscoin_miner:
    image: rnbdeploy/ducatuscoin:latest
    build:
        context: .
        dockerfile: Dockerfile
    command: bash automine.sh
    restart: always

    volumes:
      - ./testnet-conf/ducatus_test.conf:/root/.ducatuscoin/ducatuscoin.conf
      - ./.node_pwd:/root/.node_pwd

  agent:
    image: portainer/agent:2.9.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

  portainer:
    image: portainer/portainer-ce:2.9.1
    command: -H tcp://agent:9001 --tlsskipverify
    ports:
      # - "9443:9443"
      - "${PORTAINER_WEB_PORT}:9000"
      - "${PORTAINER_EDGE_PORT}:8000"
    volumes:
      - ./.docker/portainer_data:/data
  
  elasticsearch:
      image: "docker.elastic.co/elasticsearch/elasticsearch:7.2.0"
      user: "1000"
      environment:
          - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
          - "discovery.type=single-node"
      ports:
          - "${ELASTICSEARCH_PORT}:9200"
      volumes:
          - ./.docker/elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
      image: "docker.elastic.co/kibana/kibana:7.2.0"
      ports:
          - "${KIBANA_PORT}:5601"

  filebeat:
      image: "docker.elastic.co/beats/filebeat:7.2.0"
      user: root
      volumes:
          - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
          - /var/lib/docker:/var/lib/docker:ro
          - /var/run/docker.sock:/var/run/docker.sock


#volumes:
#        ducatuscoin-volume:
