version: '2'

services:
        ducatuscoin-seed:
                image: ducatuscoin
                command: bash -c 'ducatuscoind -server -listen -rpcallowip="0.0.0.0" -rpcbind="0.0.0.0" -rpcuser=user -rpcpassword=pass -addnode=ducatuscoin '
                volumes:
                        - /root/.ducatuscoin

        ducatuscoin:
                image: ducatuscoin
                links:
                        - ducatuscoin-seed
                command: bash -c 'ducatuscoind -server -listen -rpcallowip="0.0.0.0" -rpcbind="0.0.0.0" -rpcuser=user -rpcpassword=pass '
                ports:
                        - "9690:9690"
                volumes:
                        - ./data-dir:/root/.ducatuscoin

