version: '2'

services:
        ducatuscoin-seed:
                image: ducatuscoin
                command: bash -c 'ducatuscoind -server -listen -rpcallowip="0.0.0.0" -rpcbind="0.0.0.0" -rpcuser=user -rpcpassword=pass -addnode=ducatuscoin '
                volumes:
                        - /root/.ducatuscoin

        blockchain-api:
                image: ducatus-api
                command: tail -f /dev/random
                volumes:
                        - /root/.ducatuscoin
                ports:
                        - "3001:3001"


        ducatuscoin:
                image: ducatuscoin
                links:
                        - ducatuscoin-seed
                command: bash -c 'ducatuscoind -server -listen -rpcallowip="0.0.0.0" -rpcbind="0.0.0.0" -rpcuser=user -rpcpassword=pass '
                ports:
                        - "9690:9690"
                volumes:
                        - ./data-dir:/root/.ducatuscoin

