version: '2'

services:
        ducatuscoin:
                image: ducatuscoin
                command: bash -c 'ducatuscoind; sleep 1; tail -f /root/.ducatuscoin/debug.log'
                restart: always
                ports:
                        - "9690:9690"
                        - "9691:9691"
                volumes:
                        - ./data/:/root/.ducatuscoin
volumes:
        ducatuscoin-volume:
